name: java project build

on:
  push:
   branches: ["main"]
  pull_request:
   branches: ["main"]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - name: set up jdk 17
    - uses: actions/checkout@v3
      with:
       java-version: '17'
       distribution: 'temurin'
       cache: 'maven'
    - name: build with maven
      run: mvn -B package --file pom.xml

publish-job:
  runs-on: ubuntu-latest
  needs: build-test
  steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-java@v3
    with: 
      java-version: '17'
      distribution: 'temurin'
  - run: mvn --batch-mode --upgrade-snapshots veriffy 
  - run: mkdir staging && cp target/*.jar staging
  - uses: actions/upload-artifact@v3
    with:
     name: Package
     path: staging
